services:
  app :
    container_name: my-rsvp-app
    image: rsvp-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      ADMIN_USERNAME: test
      ADMIN_PASSWORD: test
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rsvp.entrypoints=https"
      - "traefik.http.routers.rsvp.rule=Host(`rsvp.test.se`)"
      - "traefik.http.routers.rsvp.tls=true"
      - "traefik.http.services.rsvp.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true